import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

function LayoutPartial({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container grow mx-auto pt-4">{children}</main>

      <footer className="container flex-none mx-auto">
        <a href="#">some footer link</a>
      </footer>
    </div>
  );
}

function LayoutNavBar({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="container mx-auto">
        <ul className="columns-3">
          <li className="font-bold underline">
            <Link href="/">Home</Link>
          </li>
          <li className="font-bold underline">
            <Link href="/posts">Posts</Link>
          </li>
        </ul>
      </div>

      {children}
    </>
  );
}

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <LayoutNavBar>
      <LayoutPartial>{children}</LayoutPartial>
    </LayoutNavBar>
  );
}
