import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { motion, useScroll } from 'framer-motion';
import { DarkModeSwitcher } from './DarkModeSwitcher';

function LayoutPartial({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>Full stack Node.js developer</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container grow mx-auto pt-4 flex flex-col gap-4">
        {children}
      </main>

      <footer className="container flex-none mx-auto">
        <a href="#">Home</a>
      </footer>
    </div>
  );
}

function LayoutNavBar({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="container mx-auto">
        <ul className="columns-3">
          <li className="font-bold underline">
            <Link href="/">Home</Link>
          </li>
          <li className="font-bold underline">
            <Link href="/posts">Posts</Link>
          </li>
          <li>
            <DarkModeSwitcher />
          </li>
        </ul>
      </div>

      {children}
    </>
  );
}

export function Layout({ children }: { children: React.ReactNode }) {
  const { scrollYProgress } = useScroll();

  return (
    <>
      <motion.div
        className="fixed h-2 inset-0 bg-slate-500 origin-[0%]"
        style={{ scaleX: scrollYProgress }}
      ></motion.div>
      <LayoutNavBar>
        <LayoutPartial>{children}</LayoutPartial>
      </LayoutNavBar>
    </>
  );
}
