import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { motion } from 'framer-motion';
import { DarkModeSwitcher } from './DarkModeSwitcher';

function LayoutPartial({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>Full stack Node.js developer</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container grow mx-auto pt-4 flex flex-col gap-4">
        {children}
      </main>

      <footer className="container flex-none mx-auto p-4">
        <a href="#">Home</a>
      </footer>
    </div>
  );
}

function LayoutNavBar({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="container mx-auto px-4">
        <ul className="columns-3 py-5">
          <li className="font-bold underline">
            <Link href="/">Home</Link>
          </li>
          <li className="font-bold underline">
            <Link href="/posts">Posts</Link>
          </li>
          <li>
            <DarkModeSwitcher />
          </li>
        </ul>
      </div>

      {children}
    </>
  );
}

export const Layout = React.forwardRef(
  (
    {
      children,
    }: {
      children: React.ReactNode;
    },
    ref?: React.Ref<HTMLDivElement> | undefined
  ) => {
    return (
      <motion.div
        ref={ref}
        className="min-h-screen bg-white dark:bg-slate-800 text-slate-900 dark:text-white "
      >
        <LayoutNavBar>
          <LayoutPartial>{children}</LayoutPartial>
        </LayoutNavBar>
      </motion.div>
    );
  }
);

Layout.displayName = 'Layout';
