import Head from 'next/head';
import Image from 'next/image';
import { Layout } from '../components/layout';
import authorPic from '../public/imgs/me.png';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
        <Image src={authorPic} alt="sergiycheck"></Image>
      </div>
      <h1 className="text-center underline font-semibold mt-4">
        Serhii Kuzmych Full stack Node.js developer
      </h1>
    </Layout>
  );
}
