import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { motion, Variants } from 'framer-motion';

import { Layout } from '../components/layout';
import authorPic from '../public/imgs/me.png';

const apperOnScreenVariants: Variants = {
  offscreen: { opacity: 0 },
  onscreen: { opacity: 1 },
};

export default function Home() {
  const [texts] = React.useState(() => {
    const textsArr = [];
    let loremExcerpt = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae iusto
    nam sed aliquam sit non facilis molestias fuga at id. Natus
    accusamus neque veritatis cupiditate incidunt saepe amet voluptates
    molestiae.`;

    for (let i = 0; i < 10; i++) {
      textsArr.push(loremExcerpt);
    }

    return textsArr;
  });

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        initial="offscreen"
        whileInView="onscreen"
        viewport={{ once: true, amount: 0.8 }}
        variants={apperOnScreenVariants}
      >
        <div className="flex justify-center">
          <Image src={authorPic} alt="sergiycheck"></Image>
        </div>

        <h1 className="text-center underline font-semibold mt-4">
          Serhii Kuzmych Full stack Node.js developer
        </h1>
      </motion.div>

      <div className="flex flex-col gap-10">
        {texts.map((text, i) => (
          <TextBlockComponent key={i} text={text} />
        ))}
      </div>
    </Layout>
  );
}

export function TextBlockComponent({ text }: { text: string }) {
  return (
    <motion.div
      initial="offscreen"
      whileInView="onscreen"
      viewport={{ once: true, amount: 0.8 }}
      className="rounded-xl border-2 border-slate-500 p-4"
      variants={apperOnScreenVariants}
    >
      <motion.p className="text-center font-medium ">{text}</motion.p>
    </motion.div>
  );
}
