import Head from 'next/head';
import { Layout } from '../components/layout';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className="text-center underline font-semibold">home heading</h2>
    </Layout>
  );
}
